export enum MetamaskErrorCodes {
  PROVIDER_NOT_INITIALIZED = 'PROVIDER_NOT_INITIALIZED',
  TRANSACTION_ERROR = 'TRANSACTION_ERROR',
  USER_DECLINED = 'USER_DECLINED',
  UNKOWN_ERROR = 'UNKOWN_ERROR',
}
