export enum MetaMaskErrorCodes {
  PROVIDER_NOT_INITIALIZED = 'PROVIDER_NOT_INITIALIZED',
  TRANSACTION_ERROR = 'TRANSACTION_ERROR',
  USER_DECLINED = 'USER_DECLINED',
  UNKOWN_ERROR = 'UNKOWN_ERROR',
  ACTION_ALREADY_PENDING = 'ACTION_ALREADY_PENDING',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  METAMASK_TERMINATED_DURING_EXECUTION = 'METAMASK_TERMINATED_DURING_EXECUTION',
}
